version: '3.8'
services:
  test-react-app:
    image: test-react-app  # Replace with the actual image name if it exists
    container_name: dockerize-vuejs-app-2
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    stdin_open: true
    tty: true
    restart: "no"
    environment:
      - CHOKIDAR_USEPOLLING=true